(source gnu)
(source melpa)
(source marmalade)

(depends-on "cedet")
(depends-on "company")
(depends-on "gist")
(depends-on "git")
(depends-on "js2-mode")
(depends-on "magit")
(depends-on "web-mode")
(depends-on "smartparens")
(depends-on "switch-window")
(depends-on "undo-tree")